# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
  - release
  - oldrel

matrix: 
  include:
  - r: devel
    warnings_are_errors: false

sudo: false
cache: packages

after_success:
    - Rscript -e 'covr::codecov()'
