# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

matrix:
  include:
  - r: devel
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
  - r: release
    name: tibble-devel
    before_script: Rscript -e "remotes::install_github('tidyverse/tibble')"
  - r: oldrel

sudo: false
cache: packages


